### ISSUE TITLE
Add the status column to your bookings table!

### ISSUE THREAD

**Issue by berlincoders** [malteasmuth/MySpaceShip#19]
Here is the step by step implementation: (provided by Olivier Girardot )

[https://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html]

rails g migration add_status_to_bookings status:integer

class AddStatusToBookings < ActiveRecord::Migration[7.0]
  def change
    add_column :bookings, :status, :integer, default: 0
  end
end

Add in your Booking model the different status you need:
class Booking < ActiveRecord::Base
  enum status: [ :pending, :rejected, :accepted ]
end
And then you can do stuff like this:
booking.status # => "pending"

# change status to "rejected"
booking.rejected!
booking.rejected? # => true
booking.status    # => "rejected"

# change status to "accepted"
booking.accepted!
booking.accepted? # => true
booking.status  # => "accepted"

etc...

**Comment by sebaspont** [comment]
Thanks, I'll take care of it!
